# LGM VIP - DATA SCIENCE (JUNE 2023)

#### NAME : ASHRAFALI.M

#### BEGINNER LEVEL TASK

### Task 2- Stock Market Prediction And Forecasting Using Stacked LSTM

Dataset link : https://raw.githubusercontent.com/mwitiderrick/stockprice/master/NSE-TATAGLOBAL.csv

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import MinMaxScaler

### Uploading Dataset 

In [2]:
data = pd.read_csv("tata.csv")

In [3]:
data

Date    Open    High     Low    Last   Close  \
0     2018-09-28  234.05  235.95  230.20  233.50  233.75   
1     2018-09-27  234.55  236.80  231.10  233.80  233.25   
2     2018-09-26  240.00  240.00  232.50  235.00  234.25   
3     2018-09-25  233.30  236.75  232.00  236.25  236.10   
4     2018-09-24  233.55  239.20  230.75  234.00  233.30   
...          ...     ...     ...     ...     ...     ...   
2030  2010-07-27  117.60  119.50  112.00  118.80  118.65   
2031  2010-07-26  120.10  121.00  117.10  117.10  117.60   
2032  2010-07-23  121.80  121.95  120.25  120.35  120.65   
2033  2010-07-22  120.30  122.00  120.25  120.75  120.90   
2034  2010-07-21  122.10  123.00  121.05  121.10  121.55   

      Total Trade Quantity  Turnover (Lacs)  
0                  3069914          7162.35  
1                  5082859         11859.95  
2                  2240909          5248.60  
3                  2349368          5503.90  
4                  3423509          7999.55  
...                    ...              ...  
2030                586100           694.98  
2031                658440           780.01  
2032                281312           340.31  
2033                293312           355.17  
2034                658666           803.56  

[2035 rows x 8 columns]

In [4]:
data.shape

(2035, 8)

In [5]:
data.columns

Index(['Date', 'Open', 'High', 'Low', 'Last', 'Close', 'Total Trade Quantity',
       'Turnover (Lacs)'],
      dtype='object')

In [6]:
data.isnull()

Date   Open   High    Low   Last  Close  Total Trade Quantity  \
0     False  False  False  False  False  False                 False   
1     False  False  False  False  False  False                 False   
2     False  False  False  False  False  False                 False   
3     False  False  False  False  False  False                 False   
4     False  False  False  False  False  False                 False   
...     ...    ...    ...    ...    ...    ...                   ...   
2030  False  False  False  False  False  False                 False   
2031  False  False  False  False  False  False                 False   
2032  False  False  False  False  False  False                 False   
2033  False  False  False  False  False  False                 False   
2034  False  False  False  False  False  False                 False   

      Turnover (Lacs)  
0               False  
1               False  
2               False  
3               False  
4               False  
...               ...  
2030            False  
2031            False  
2032            False  
2033            False  
2034            False  

[2035 rows x 8 columns]

In [7]:
data.head

<bound method NDFrame.head of             Date    Open    High     Low    Last   Close  \
0     2018-09-28  234.05  235.95  230.20  233.50  233.75   
1     2018-09-27  234.55  236.80  231.10  233.80  233.25   
2     2018-09-26  240.00  240.00  232.50  235.00  234.25   
3     2018-09-25  233.30  236.75  232.00  236.25  236.10   
4     2018-09-24  233.55  239.20  230.75  234.00  233.30   
...          ...     ...     ...     ...     ...     ...   
2030  2010-07-27  117.60  119.50  112.00  118.80  118.65   
2031  2010-07-26  120.10  121.00  117.10  117.10  117.60   
2032  2010-07-23  121.80  121.95  120.25  120.35  120.65   
2033  2010-07-22  120.30  122.00  120.25  120.75  120.90   
2034  2010-07-21  122.10  123.00  121.05  121.10  121.55   

      Total Trade Quantity  Turnover (Lacs)  
0                  3069914          7162.35  
1                  5082859         11859.95  
2                  2240909          5248.60  
3                  2349368          5503.90  
4                  

In [8]:
data.isnull().sum()


Date                    0
Open                    0
High                    0
Low                     0
Last                    0
Close                   0
Total Trade Quantity    0
Turnover (Lacs)         0
dtype: int64

In [9]:
duplicates= data.duplicated()
duplicates.value_counts()

False    2035
dtype: int64

In [10]:
X= data.drop('Close',axis=1)

In [11]:
y=data['Close']

In [12]:
X

Date    Open    High     Low    Last  Total Trade Quantity  \
0     2018-09-28  234.05  235.95  230.20  233.50               3069914   
1     2018-09-27  234.55  236.80  231.10  233.80               5082859   
2     2018-09-26  240.00  240.00  232.50  235.00               2240909   
3     2018-09-25  233.30  236.75  232.00  236.25               2349368   
4     2018-09-24  233.55  239.20  230.75  234.00               3423509   
...          ...     ...     ...     ...     ...                   ...   
2030  2010-07-27  117.60  119.50  112.00  118.80                586100   
2031  2010-07-26  120.10  121.00  117.10  117.10                658440   
2032  2010-07-23  121.80  121.95  120.25  120.35                281312   
2033  2010-07-22  120.30  122.00  120.25  120.75                293312   
2034  2010-07-21  122.10  123.00  121.05  121.10                658666   

      Turnover (Lacs)  
0             7162.35  
1            11859.95  
2             5248.60  
3             5503.90  
4             7999.55  
...               ...  
2030           694.98  
2031           780.01  
2032           340.31  
2033           355.17  
2034           803.56  

[2035 rows x 7 columns]

In [13]:
y

0       233.75
1       233.25
2       234.25
3       236.10
4       233.30
         ...  
2030    118.65
2031    117.60
2032    120.65
2033    120.90
2034    121.55
Name: Close, Length: 2035, dtype: float64

### Preprocess the data

In [14]:
sc = MinMaxScaler(feature_range=(0, 1))
scaled_data = sc.fit_transform(data['Close'].values.reshape(-1, 1))

### Split the data into training and testing sets

In [15]:
train_size = int(len(scaled_data) * 0.8)
train_data = scaled_data[:train_size]
test_data = scaled_data[train_size:]

 Define the function to create input and output sequences

In [16]:
def create_sequences(data, seq_length):
    x = []
    y = []
    for i in range(len(data) - seq_length):
        x.append(data[i:i+seq_length])
        y.append(data[i+seq_length])
    return np.array(x), np.array(y)

In [17]:
sequence_length = 20

Create the training sequences

In [18]:
x_train, y_train = create_sequences(train_data, sequence_length)

In [19]:
x_train

array([[[0.62418301],
        [0.62214052],
        [0.62622549],
        ...,
        [0.63623366],
        [0.62642974],
        [0.63337418]],

       [[0.62214052],
        [0.62622549],
        [0.63378268],
        ...,
        [0.62642974],
        [0.63337418],
        [0.62745098]],

       [[0.62622549],
        [0.63378268],
        [0.62234477],
        ...,
        [0.63337418],
        [0.62745098],
        [0.62254902]],

       ...,

       [[0.14705882],
        [0.15012255],
        [0.15522876],
        ...,
        [0.15175654],
        [0.14644608],
        [0.15216503]],

       [[0.15012255],
        [0.15522876],
        [0.14052288],
        ...,
        [0.14644608],
        [0.15216503],
        [0.1435866 ]],

       [[0.15522876],
        [0.14052288],
        [0.12826797],
        ...,
        [0.15216503],
        [0.1435866 ],
        [0.13419118]]])

In [20]:
y_train

array([[0.62745098],
       [0.62254902],
       [0.6376634 ],
       ...,
       [0.1435866 ],
       [0.13419118],
       [0.1431781 ]])

 Create the testing sequences

In [21]:
x_test, y_test = create_sequences(test_data, sequence_length)

In [22]:
x_test

array([[[0.16115196],
        [0.16176471],
        [0.17320261],
        ...,
        [0.1503268 ],
        [0.13255719],
        [0.14338235]],

       [[0.16176471],
        [0.17320261],
        [0.18218954],
        ...,
        [0.13255719],
        [0.14338235],
        [0.15849673]],

       [[0.17320261],
        [0.18218954],
        [0.16237745],
        ...,
        [0.14338235],
        [0.15849673],
        [0.1186683 ]],

       ...,

       [[0.12479575],
        [0.13112745],
        [0.11397059],
        ...,
        [0.15236928],
        [0.15400327],
        [0.14971405]],

       [[0.13112745],
        [0.11397059],
        [0.1190768 ],
        ...,
        [0.15400327],
        [0.14971405],
        [0.1621732 ]],

       [[0.11397059],
        [0.1190768 ],
        [0.12377451],
        ...,
        [0.14971405],
        [0.1621732 ],
        [0.16319444]]])

In [23]:
y_test

array([[0.15849673],
       [0.1186683 ],
       [0.11519608],
       [0.10947712],
       [0.0692402 ],
       [0.06597222],
       [0.05841503],
       [0.05044935],
       [0.04534314],
       [0.04779412],
       [0.05290033],
       [0.04922386],
       [0.06638072],
       [0.07169118],
       [0.05392157],
       [0.04881536],
       [0.04881536],
       [0.05310458],
       [0.04963235],
       [0.05065359],
       [0.05126634],
       [0.04963235],
       [0.05902778],
       [0.05555556],
       [0.04084967],
       [0.03737745],
       [0.03737745],
       [0.02655229],
       [0.02879902],
       [0.0316585 ],
       [0.0316585 ],
       [0.03635621],
       [0.02205882],
       [0.01674837],
       [0.01450163],
       [0.02226307],
       [0.03615196],
       [0.02675654],
       [0.03206699],
       [0.02696078],
       [0.03574346],
       [0.03594771],
       [0.04044118],
       [0.03921569],
       [0.04411765],
       [0.02982026],
       [0.0122549 ],
       [0.012

### Build the stacked LSTM model

In [24]:
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1], 1)))
model.add(LSTM(units=50, return_sequences=True))
model.add(LSTM(units=50))
model.add(Dense(units=1))


Compile the model

In [25]:
model.compile(optimizer='adam', loss='mean_squared_error')

### Train the model

In [26]:
model.fit(x_train, y_train, epochs=30, batch_size=32)

Epoch 1/30
51/51 [==============================] - 6s 27ms/step - loss: 0.0141
Epoch 2/30
51/51 [==============================] - 1s 26ms/step - loss: 0.0017
Epoch 3/30
51/51 [==============================] - 1s 27ms/step - loss: 0.0016
Epoch 4/30
51/51 [==============================] - 1s 27ms/step - loss: 0.0015
Epoch 5/30
51/51 [==============================] - 1s 27ms/step - loss: 0.0015
Epoch 6/30
51/51 [==============================] - 1s 26ms/step - loss: 0.0015
Epoch 7/30
51/51 [==============================] - 1s 27ms/step - loss: 0.0013
Epoch 8/30
51/51 [==============================] - 1s 27ms/step - loss: 0.0012
Epoch 9/30
51/51 [==============================] - 1s 28ms/step - loss: 0.0011
Epoch 10/30
51/51 [==============================] - 1s 27ms/step - loss: 9.8531e-04
Epoch 11/30
51/51 [==============================] - 1s 28ms/step - loss: 0.0011
Epoch 12/30
51/51 [==============================] - 1s 28ms/step - loss: 9.2766e-04
Epoch 13/30
51/51 [==========

Make predictions

In [27]:
predictions = model.predict(x_test)

13/13 [==============================] - 1s 10ms/step


### Evaluate the model

In [28]:
predictions = sc.inverse_transform(predictions)

In [29]:
rmse = np.sqrt(np.mean((predictions - sc.inverse_transform(y_test))**2))
print('Root Mean Squared Error:', rmse)

Root Mean Squared Error: 4.586005306668979
